### ISSUE TITLE
A11y accessibility defect: Tables should not be used in this topic

### ISSUE THREAD

**Issue by jpkessle** [IBM-Bluemix-Docs/dbaas-cli-plugin#1]
I am the core CLI doc owner and we are checking for accessibility issues in our documentation (cloud.ibm.com/docs/cli). It was observed that this this topic needs to have all the tables removed and re-worked (to not use tables).

See the following topic as an example for proper syntax:

IBM Cloud Container Registry CLI
https://cloud.ibm.com/docs/container-registry-cli-plugin?topic=container-registry-cli-plugin-containerregcli

Please contact me if you have any questions. 
joshkess@us.ibm.com

**Comment by jpkessle** [comment]
@GRZEMBA Is this something you can help with? Please let me know if you are not the right contact.

**Comment by jpkessle** [comment]
Changes have been made to staging here:

IBM Cloud Hyper Protect DBaaS CLI plug-in
https://test.cloud.ibm.com/docs/dbaas-cli-plugin?topic=dbaas-cli-plugin-dbaas_cli_plugin

Content owner is waiting for prod access to promote changes.

**Comment by liuxjep** [comment]
@jpkessle 
Hi Josh,

I have updated the prod repo. Now it is available at: https://cloud.ibm.com/docs/dbaas-cli-plugin?topic=dbaas-cli-plugin-dbaas_cli_plugin

There is one thing I'd like to mention here is that I also modified the subcollection and TOC, which makes the current reuse link (/dbaas-cli-plugin/hyper-protect-dbaas-dbaas_cli_plugin) in the cloud cli repo no longer available. The new reuse link of DBaaS CLI should be: **/dbaas-cli-plugin/dbaas-cli-plugin-dbaas_cli_plugin**.

If there are any problems, please let me know.

Thank you!

**Comment by jpkessle** [comment]
@liuxjep Awesome thank you so much! I have updated the CLI link in prod and it will be published soon.
